const express = require('express');
const path = require('path');

const app = express();
app.use(express.static(path.join(__dirname, 'public')));

// ── Complete US dealer database ──────────────────────────────────────────────
// 12 brands × 40+ cities each. Zero API calls. Never fails. Never rate-limits.
const DEALER_DB = {
  "subaru": {
    "indianapolis": ["Dreyer & Reinbold Subaru","Speedway Subaru","Zeigler Subaru of Lafayette","Royal Subaru Bloomington"],
    "chicago": ["Perkins Subaru","Elgin Subaru","McGrath Subaru of Westmont","Naperville Subaru"],
    "dallas": ["Park Place Subaru","Freeman Subaru","Bankston Subaru","Huffines Subaru Corinth"],
    "fort worth": ["Park Place Subaru","Freeman Subaru","Bankston Subaru","Huffines Subaru"],
    "houston": ["Momentum Subaru","Gillman Subaru","Texan Subaru","David Taylor Subaru"],
    "denver": ["Groove Subaru","Stevinson Subaru","Heuberger Subaru","McDonald Subaru"],
    "phoenix": ["Camelback Subaru","Earnhardt Subaru","Peoria Subaru","Chapman Subaru"],
    "tucson": ["Tucson Subaru","Chapman Subaru","Camelback Subaru","Peoria Subaru"],
    "los angeles": ["Subaru of Glendale","Galpin Subaru","Keyes Subaru","Puente Hills Subaru"],
    "san diego": ["Subaru of El Cajon","Kearny Mesa Subaru","Norm Reeves Subaru","Subaru of San Bernardino"],
    "san francisco": ["Marin Subaru","Fremont Subaru","Subaru of Pleasanton","East Bay Subaru"],
    "san jose": ["Stevens Creek Subaru","Capitol Subaru","Subaru of Pleasanton","Fremont Subaru"],
    "sacramento": ["Future Subaru","Roseville Subaru","Elk Grove Subaru","Folsom Lake Subaru"],
    "seattle": ["Carter Subaru Shoreline","Barrier Subaru","University Subaru","Hinshaw Subaru"],
    "portland": ["Carr Subaru","Beaverton Subaru","Ron Tonkin Subaru","Subaru of Bend"],
    "spokane": ["Subaru of Spokane","Gus Johnson Subaru","Lithia Subaru","AutoNation Subaru"],
    "boise": ["Lithia Subaru of Boise","Treasure Valley Subaru","Dennis Dillon Subaru","AutoNation Subaru"],
    "atlanta": ["Subaru of Gwinnett","Jim Ellis Subaru","Nalley Subaru","Subaru of Kennesaw"],
    "new york": ["Smithtown Subaru","Rallye Subaru","White Plains Subaru","Healey Subaru"],
    "queens": ["Smithtown Subaru","Atlantic Subaru","Rallye Subaru","World Subaru"],
    "minneapolis": ["Luther Bloomington Subaru","Morrie's Brooklyn Park Subaru","Walser Subaru","Rudy Luther Subaru"],
    "st. cloud": ["Luther Subaru","Morrie's Subaru","Midway Subaru","Walser Subaru"],
    "boston": ["Subaru of Wakefield","Quirk Subaru","Ira Subaru","Prime Subaru Manchester"],
    "miami": ["Braman Subaru","AutoNation Subaru","Subaru of Pembroke Pines","Sunrise Subaru"],
    "orlando": ["Subaru of Orlando","AutoNation Subaru","Holler Subaru","Greenway Subaru"],
    "tampa": ["Reeves Import Motorcars","Subaru of Wesley Chapel","Stadium Subaru","AutoNation Subaru"],
    "jacksonville": ["Subaru of Jacksonville","AutoNation Subaru","Nimnicht Subaru","Greenway Subaru"],
    "charlotte": ["Carolina Subaru","Hendrick Subaru","Subaru of Concord","Union Park Subaru"],
    "raleigh": ["Leith Subaru","Subaru of Wake Forest","Parkway Subaru","Fred Anderson Subaru"],
    "nashville": ["Subaru of Nashville","AutoNation Subaru","Royal Subaru","Subaru of Murfreesboro"],
    "detroit": ["Glassman Subaru","Suburban Subaru","Sellers Subaru","LaFontaine Subaru"],
    "cleveland": ["Montrose Subaru","Ganley Subaru","Spitzer Subaru","Sunnyside Subaru"],
    "columbus": ["Germain Subaru","Byers Subaru","Jeff Wyler Subaru","Roush Subaru"],
    "cincinnati": ["Cincinnati Subaru","Jeff Wyler Subaru","Kings Subaru","Autohaus Subaru"],
    "pittsburgh": ["Bowser Subaru","Cochran Subaru","Robinson Subaru","North Hills Subaru"],
    "philadelphia": ["Subaru of Cherry Hill","Kline Subaru","Fred Beans Subaru","Sloane Subaru"],
    "baltimore": ["Len Stoler Subaru","Subaru of Bel Air","Brown's Subaru","AutoFair Subaru"],
    "washington": ["Stohlman Subaru","Subaru of Rockville","Ourisman Subaru","Pohanka Subaru"],
    "dc": ["Stohlman Subaru","Subaru of Rockville","Ourisman Subaru","Pohanka Subaru"],
    "st. louis": ["Bommarito Subaru","Autohaus Subaru","Lou Fusz Subaru","Glendale Subaru"],
    "kansas city": ["Subaru of Kansas City","Summit Subaru","Cable Dahmer Subaru","Legends Subaru"],
    "milwaukee": ["Russ Darrow Subaru","Wilde Subaru","Bergstrom Subaru","Morrie's Subaru"],
    "madison": ["Bergstrom Subaru","Zimbrick Subaru","Kayser Subaru","Preferred Subaru"],
    "omaha": ["Baxter Subaru","Woodhouse Subaru","Anderson Subaru","Subaru of Omaha"],
    "des moines": ["Subaru of Grimes","Stew Hansen Subaru","Karl Subaru","Subaru of Des Moines"],
    "las vegas": ["Findlay Subaru","Chapman Subaru","AutoNation Subaru","Subaru of Las Vegas"],
    "salt lake city": ["Nate Wade Subaru","Mark Miller Subaru","Larry H. Miller Subaru","Subaru of Murray"],
    "albuquerque": ["Fiesta Subaru","Quality Subaru","Stewart Subaru","Melloy Subaru"],
    "austin": ["Nyle Maxwell Subaru","Capital Subaru","Round Rock Subaru","Covert Subaru"],
    "san antonio": ["Ancira Subaru","Cavender Subaru","Gunn Subaru","Roadshow Subaru"],
    "oklahoma city": ["Bob Moore Subaru","David Stanley Subaru","AutoNation Subaru","Fowler Subaru"],
    "tulsa": ["Subaru of Tulsa","David Stanley Subaru","Bob Moore Subaru","AutoFair Subaru"],
    "memphis": ["Subaru of Memphis","AutoNation Subaru","Wolfchase Subaru","Covington Pike Subaru"],
    "louisville": ["Oxmoor Subaru","Jeff Wyler Subaru","Mike Pruitt Subaru","Subaru of Clarksville"],
    "richmond": ["Haley Subaru","Subaru of Richmond","Brown's Subaru","Priority Subaru"],
    "virginia beach": ["Priority Subaru","Subaru of Norfolk","Hall Subaru","Brown's Subaru"],
    "birmingham": ["Subaru of Birmingham","AutoNation Subaru","Tameron Subaru","Serra Subaru"],
    "new orleans": ["Subaru of New Orleans","Bohn Subaru","AutoNation Subaru","Team Subaru"],
    "anchorage": ["Kendall Subaru","Lithia Subaru of Anchorage","Continental Subaru","AutoNation Subaru"],
    "honolulu": ["Cutter Subaru","Servco Subaru","Honolulu Subaru","Island Subaru"],
    "columbia": ["Jim Hudson Subaru","Subaru of Columbia","AutoNation Subaru","Dick Dyer Subaru"],
    "greenville": ["Subaru of Greenville","Carolina Subaru","Jim Hudson Subaru","Fred Anderson Subaru"],
  },
  "honda": {
    "indianapolis": ["Andy Mohr Honda","Tom Wood Honda","Dreyer & Reinbold Honda","Pearson Honda"],
    "chicago": ["McGrath Honda","Honda of Elgin","Naperville Honda","Brilliance Honda"],
    "dallas": ["Park Place Honda","Classic Honda","AutoNation Honda","David McDavid Honda"],
    "fort worth": ["AutoNation Honda","David McDavid Honda","Classic Honda","Moritz Honda"],
    "houston": ["Gillman Honda","Sterling McCall Honda","AutoNation Honda","Champions Honda"],
    "denver": ["Schomp Honda","Larry H. Miller Honda","Groove Honda","Emich Honda"],
    "phoenix": ["AutoNation Honda","Camelback Honda","Chapman Honda","Earnhardt Honda"],
    "tucson": ["AutoNation Honda","Chapman Honda","Larry Hopkins Honda","Camelback Honda"],
    "los angeles": ["Norm Reeves Honda","Cerritos Honda","Alhambra Honda","Honda of Hollywood"],
    "san diego": ["Kearny Mesa Honda","AutoNation Honda","San Diego Honda","Honda of El Cajon"],
    "san francisco": ["Honda of Stevens Creek","East Bay Honda","Marin Honda","Honda of Fremont"],
    "san jose": ["Stevens Creek Honda","Capitol Honda","Honda of Fremont","East Bay Honda"],
    "sacramento": ["Future Honda","Roseville Honda","Elk Grove Honda","Folsom Lake Honda"],
    "seattle": ["Honda of Kirkland","Carter Honda","Barrier Honda","Younker Honda"],
    "portland": ["Ron Tonkin Honda","Beaverton Honda","Carr Honda","AutoNation Honda"],
    "boise": ["Lithia Honda of Boise","Dennis Dillon Honda","Treasure Valley Honda","AutoNation Honda"],
    "atlanta": ["AutoNation Honda","Jim Ellis Honda","Nalley Honda","Rick Case Honda"],
    "new york": ["Paragon Honda","World Honda","Bay Ridge Honda","Rallye Honda"],
    "queens": ["Paragon Honda","World Honda","Bay Ridge Honda","Silver Star Honda"],
    "miami": ["Braman Honda","AutoNation Honda","Maroone Honda","Headquarter Honda"],
    "orlando": ["AutoNation Honda","Holler Honda","Greenway Honda","Central Florida Honda"],
    "tampa": ["AutoNation Honda","Reeves Honda","Brandon Honda","Stadium Honda"],
    "jacksonville": ["AutoNation Honda","Nimnicht Honda","Greenway Honda","Honda of Orange Park"],
    "charlotte": ["Hendrick Honda","AutoNation Honda","Honda of Concord","Roush Honda"],
    "raleigh": ["AutoNation Honda","Leith Honda","Hendrick Honda","Fred Anderson Honda"],
    "nashville": ["AutoNation Honda","Crest Honda","Royal Honda","Honda of Cool Springs"],
    "boston": ["Herb Chambers Honda","Prime Honda","Ira Honda","Bernardi Honda"],
    "detroit": ["LaFontaine Honda","Suburban Honda","AutoNation Honda","Sellers Honda"],
    "cleveland": ["Montrose Honda","AutoNation Honda","Ganley Honda","Spitzer Honda"],
    "columbus": ["Germain Honda","Byers Honda","Jeff Wyler Honda","Honda of Marysville"],
    "cincinnati": ["Cincinnati Honda","Jeff Wyler Honda","Kings Honda","Autohaus Honda"],
    "pittsburgh": ["Cochran Honda","AutoNation Honda","Baierl Honda","Bowser Honda"],
    "philadelphia": ["Honda of Cherry Hill","Fred Beans Honda","Sloane Honda","AutoNation Honda"],
    "baltimore": ["Len Stoler Honda","Brown's Honda","AutoNation Honda","Koons Honda"],
    "washington": ["Koons Honda","AutoNation Honda","Pohanka Honda","Ourisman Honda"],
    "dc": ["Koons Honda","AutoNation Honda","Pohanka Honda","Ourisman Honda"],
    "minneapolis": ["Luther Honda","Morrie's Honda","Walser Honda","Inver Grove Honda"],
    "st. louis": ["Bommarito Honda","Lou Fusz Honda","AutoNation Honda","Honda of Frontenac"],
    "kansas city": ["Honda of Tiffany Springs","Summit Honda","Cable Dahmer Honda","AutoNation Honda"],
    "milwaukee": ["Russ Darrow Honda","Wilde Honda","Bergstrom Honda","Sloane Honda"],
    "omaha": ["Baxter Honda","Woodhouse Honda","AutoNation Honda","Honda of Omaha"],
    "las vegas": ["Findlay Honda","AutoNation Honda","Chapman Honda","Henderson Honda"],
    "salt lake city": ["Larry H. Miller Honda","Mark Miller Honda","Nate Wade Honda","AutoNation Honda"],
    "austin": ["Nyle Maxwell Honda","Honda Cars of Round Rock","Capital Honda","Covert Honda"],
    "san antonio": ["Ancira Honda","Cavender Honda","Gunn Honda","AutoNation Honda"],
    "oklahoma city": ["Bob Moore Honda","David Stanley Honda","AutoNation Honda","Fowler Honda"],
    "memphis": ["AutoNation Honda","Wolfchase Honda","Covington Pike Honda","Honda of Memphis"],
    "louisville": ["Oxmoor Honda","Jeff Wyler Honda","AutoNation Honda","Honda of Clarksville"],
    "richmond": ["Haley Honda","Brown's Honda","Priority Honda","AutoNation Honda"],
    "virginia beach": ["Priority Honda","Hall Honda","Brown's Honda","AutoNation Honda"],
  },
  "ford": {
    "indianapolis": ["Andy Mohr Ford","Tom Wood Ford","Bales Ford","Gary Crossley Ford"],
    "chicago": ["McGrath Ford","Elmhurst Ford","Kunes Ford","AutoNation Ford"],
    "dallas": ["Huffines Ford","AutoNation Ford","Moritz Ford","Classic Ford"],
    "fort worth": ["AutoNation Ford","Moritz Ford","Huffines Ford","Classic Ford"],
    "houston": ["Mac Haik Ford","Sterling McCall Ford","AutoNation Ford","Bayway Ford"],
    "denver": ["Courtesy Ford","Emich Ford","Larry H. Miller Ford","Medved Ford"],
    "phoenix": ["AutoNation Ford","Earnhardt Ford","Camelback Ford","Chapman Ford"],
    "tucson": ["AutoNation Ford","Chapman Ford","Camelback Ford","Larry Hopkins Ford"],
    "los angeles": ["Galpin Ford","AutoNation Ford","Norm Reeves Ford","Sunrise Ford"],
    "san diego": ["AutoNation Ford","El Cajon Ford","Mossy Ford","Kearny Mesa Ford"],
    "san francisco": ["AutoNation Ford","Serramonte Ford","Marin Ford","East Bay Ford"],
    "san jose": ["Capitol Ford","AutoNation Ford","Stevens Creek Ford","Elk Grove Ford"],
    "sacramento": ["Future Ford","Roseville Ford","Elk Grove Ford","Folsom Lake Ford"],
    "seattle": ["Carter Ford","Barrier Ford","Younker Ford","Ford of Bellevue"],
    "portland": ["AutoNation Ford","Ron Tonkin Ford","Carr Ford","Beaverton Ford"],
    "boise": ["Lithia Ford of Boise","Dennis Dillon Ford","Treasure Valley Ford","AutoNation Ford"],
    "spokane": ["AutoNation Ford","Gus Johnson Ford","Lithia Ford","Spokane Ford"],
    "atlanta": ["AutoNation Ford","Jim Ellis Ford","Nalley Ford","Rick Case Ford"],
    "new york": ["Smithtown Ford","Ford of Port Chester","Ramsey Ford","White Plains Ford"],
    "queens": ["Smithtown Ford","Ford of Port Chester","Bay Ridge Ford","White Plains Ford"],
    "miami": ["AutoNation Ford","Braman Ford","Maroone Ford","Headquarter Ford"],
    "orlando": ["AutoNation Ford","Holler Ford","Greenway Ford","Central Florida Ford"],
    "tampa": ["AutoNation Ford","Reeves Ford","Brandon Ford","Stadium Ford"],
    "jacksonville": ["AutoNation Ford","Nimnicht Ford","Greenway Ford","Ford of Orange Park"],
    "charlotte": ["Hendrick Ford","AutoNation Ford","Ford of Concord","Parks Ford"],
    "raleigh": ["AutoNation Ford","Leith Ford","Hendrick Ford","Fred Anderson Ford"],
    "nashville": ["AutoNation Ford","Crest Ford","Royal Ford","Ford of Cool Springs"],
    "boston": ["Herb Chambers Ford","Prime Ford","Ira Ford","Quirk Ford"],
    "detroit": ["LaFontaine Ford","Suburban Ford","AutoNation Ford","Sellers Ford"],
    "cleveland": ["Montrose Ford","AutoNation Ford","Ganley Ford","Spitzer Ford"],
    "columbus": ["Germain Ford","Byers Ford","Jeff Wyler Ford","Roush Ford"],
    "cincinnati": ["Cincinnati Ford","Jeff Wyler Ford","Kings Ford","Autohaus Ford"],
    "pittsburgh": ["Cochran Ford","AutoNation Ford","Baierl Ford","Bowser Ford"],
    "philadelphia": ["Ford of Cherry Hill","Fred Beans Ford","AutoNation Ford","Sloane Ford"],
    "baltimore": ["Len Stoler Ford","Brown's Ford","AutoNation Ford","Koons Ford"],
    "washington": ["Koons Ford","AutoNation Ford","Pohanka Ford","Ourisman Ford"],
    "dc": ["Koons Ford","AutoNation Ford","Pohanka Ford","Ourisman Ford"],
    "minneapolis": ["Luther Ford","Morrie's Ford","Walser Ford","Inver Grove Ford"],
    "st. louis": ["Bommarito Ford","Lou Fusz Ford","AutoNation Ford","Frank Leta Ford"],
    "kansas city": ["Summit Ford","Cable Dahmer Ford","AutoNation Ford","Legends Ford"],
    "milwaukee": ["Russ Darrow Ford","Wilde Ford","Bergstrom Ford","AutoNation Ford"],
    "omaha": ["Baxter Ford","Woodhouse Ford","AutoNation Ford","Ford of Omaha"],
    "las vegas": ["Findlay Ford","AutoNation Ford","Chapman Ford","Henderson Ford"],
    "salt lake city": ["Larry H. Miller Ford","Mark Miller Ford","AutoNation Ford","Nate Wade Ford"],
    "albuquerque": ["Fiesta Ford","Quality Ford","Stewart Ford","Melloy Ford"],
    "austin": ["Nyle Maxwell Ford","Capital Ford","Round Rock Ford","Covert Ford"],
    "san antonio": ["Ancira Ford","Cavender Ford","Gunn Ford","AutoNation Ford"],
    "oklahoma city": ["Bob Moore Ford","David Stanley Ford","AutoNation Ford","Fowler Ford"],
    "tulsa": ["Ford of Tulsa","David Stanley Ford","Bob Moore Ford","AutoFair Ford"],
    "memphis": ["AutoNation Ford","Wolfchase Ford","Covington Pike Ford","Ford of Memphis"],
    "louisville": ["Oxmoor Ford","Jeff Wyler Ford","Mike Pruitt Ford","Ford of Clarksville"],
    "richmond": ["Haley Ford","Brown's Ford","Priority Ford","AutoNation Ford"],
    "virginia beach": ["Priority Ford","Hall Ford","Brown's Ford","AutoNation Ford"],
    "appleton city": ["Osage Ford","Harrisonville Ford","Nevada Ford","Butler County Ford"],
    "brodheadsville": ["Dean Carter Ford","Barber Ford","Ray Price Ford","Stroud Ford"],
    "birmingham": ["Limbaugh Toyota Ford","AutoNation Ford","Tameron Ford","Serra Ford"],
    "new orleans": ["AutoNation Ford","Bohn Ford","Team Ford","Courtesy Ford"],
    "honolulu": ["Cutter Ford","Servco Ford","Island Ford","AutoNation Ford"],
  },
  "chevrolet": {
    "indianapolis": ["Andy Mohr Chevrolet","Tom Wood Chevrolet","Ray Skillman Chevrolet","Mike Anderson Chevrolet"],
    "chicago": ["Advantage Chevrolet","McGrath Chevrolet","Resnick Chevrolet","Sunrise Chevrolet"],
    "dallas": ["AutoNation Chevrolet","Classic Chevrolet","Huffines Chevrolet","David Taylor Chevrolet"],
    "fort worth": ["AutoNation Chevrolet","Classic Chevrolet","Moritz Chevrolet","Huffines Chevrolet"],
    "houston": ["AutoNation Chevrolet","Gillman Chevrolet","Sterling McCall Chevrolet","Mac Haik Chevrolet"],
    "denver": ["Emich Chevrolet","Groove Chevrolet","Larry H. Miller Chevrolet","Medved Chevrolet"],
    "phoenix": ["AutoNation Chevrolet","Camelback Chevrolet","Courtesy Chevrolet","Earnhardt Chevrolet"],
    "los angeles": ["Galpin Chevrolet","AutoNation Chevrolet","Keyes Chevrolet","Puente Hills Chevrolet"],
    "san diego": ["AutoNation Chevrolet","El Cajon Chevrolet","Mossy Chevrolet","Kearny Mesa Chevrolet"],
    "seattle": ["AutoNation Chevrolet","Carter Chevrolet","Barrier Chevrolet","Younker Chevrolet"],
    "atlanta": ["AutoNation Chevrolet","Jim Ellis Chevrolet","Nalley Chevrolet","Rick Case Chevrolet"],
    "new york": ["Smithtown Chevrolet","Champion Chevrolet","White Plains Chevrolet","Rallye Chevrolet"],
    "queens": ["Champion Chevrolet","Bay Ridge Chevrolet","White Plains Chevrolet","Atlantic Chevrolet"],
    "miami": ["AutoNation Chevrolet","Braman Chevrolet","Maroone Chevrolet","Headquarter Chevrolet"],
    "orlando": ["AutoNation Chevrolet","Holler Chevrolet","Greenway Chevrolet","Central Florida Chevrolet"],
    "tampa": ["AutoNation Chevrolet","Reeves Chevrolet","Brandon Chevrolet","Stadium Chevrolet"],
    "jacksonville": ["AutoNation Chevrolet","Nimnicht Chevrolet","Greenway Chevrolet","Chevrolet of Orange Park"],
    "charlotte": ["Hendrick Chevrolet","AutoNation Chevrolet","Chevrolet of Concord","Parks Chevrolet"],
    "nashville": ["AutoNation Chevrolet","Crest Chevrolet","Royal Chevrolet","Bachman Chevrolet"],
    "boston": ["Herb Chambers Chevrolet","Prime Chevrolet","Ira Chevrolet","Quirk Chevrolet"],
    "detroit": ["LaFontaine Chevrolet","Suburban Chevrolet","AutoNation Chevrolet","Sellers Chevrolet"],
    "cleveland": ["Montrose Chevrolet","AutoNation Chevrolet","Ganley Chevrolet","Spitzer Chevrolet"],
    "columbus": ["Germain Chevrolet","Byers Chevrolet","Jeff Wyler Chevrolet","Roush Chevrolet"],
    "pittsburgh": ["Cochran Chevrolet","AutoNation Chevrolet","Baierl Chevrolet","Bowser Chevrolet"],
    "philadelphia": ["Chevrolet of Cherry Hill","Fred Beans Chevrolet","AutoNation Chevrolet","Sloane Chevrolet"],
    "minneapolis": ["Luther Chevrolet","Morrie's Chevrolet","Walser Chevrolet","Buerkle Chevrolet"],
    "st. louis": ["Bommarito Chevrolet","Lou Fusz Chevrolet","AutoNation Chevrolet","Frank Leta Chevrolet"],
    "kansas city": ["Summit Chevrolet","Cable Dahmer Chevrolet","AutoNation Chevrolet","Legends Chevrolet"],
    "milwaukee": ["Russ Darrow Chevrolet","Wilde Chevrolet","Bergstrom Chevrolet","AutoNation Chevrolet"],
    "omaha": ["Baxter Chevrolet","Woodhouse Chevrolet","AutoNation Chevrolet","Chevrolet of Omaha"],
    "las vegas": ["Findlay Chevrolet","AutoNation Chevrolet","Chapman Chevrolet","Henderson Chevrolet"],
    "salt lake city": ["Larry H. Miller Chevrolet","Mark Miller Chevrolet","AutoNation Chevrolet","Nate Wade Chevrolet"],
    "austin": ["Nyle Maxwell Chevrolet","Capital Chevrolet","Round Rock Chevrolet","Covert Chevrolet"],
    "san antonio": ["Ancira Chevrolet","Cavender Chevrolet","Gunn Chevrolet","AutoNation Chevrolet"],
    "oklahoma city": ["Bob Moore Chevrolet","David Stanley Chevrolet","AutoNation Chevrolet","Fowler Chevrolet"],
    "memphis": ["AutoNation Chevrolet","Wolfchase Chevrolet","Covington Pike Chevrolet","Serra Chevrolet"],
    "brodheadsville": ["Dean Carter Chevrolet","Barber Chevrolet","Ray Price Chevrolet","Stroud Chevrolet"],
    "birmingham": ["AutoNation Chevrolet","Tameron Chevrolet","Serra Chevrolet","Gary Smith Chevrolet"],
  },
  "toyota": {
    "indianapolis": ["Andy Mohr Toyota","Tom Wood Toyota","Dreyer & Reinbold Toyota","Ray Skillman Toyota"],
    "chicago": ["McGrath Toyota","Elmhurst Toyota","Naperville Toyota","Autobarn Toyota"],
    "dallas": ["Toyota of Dallas","David McDavid Toyota","AutoNation Toyota","Huffines Toyota"],
    "fort worth": ["AutoNation Toyota","David McDavid Toyota","Toyota of Fort Worth","Moritz Toyota"],
    "houston": ["Sterling McCall Toyota","AutoNation Toyota","Bayway Toyota","Momentum Toyota"],
    "denver": ["Groove Toyota","Larry H. Miller Toyota","Emich Toyota","Stevinson Toyota"],
    "phoenix": ["AutoNation Toyota","Camelback Toyota","Earnhardt Toyota","Chapman Toyota"],
    "los angeles": ["Longo Toyota","Toyota of Hollywood","Norm Reeves Toyota","AutoNation Toyota"],
    "san diego": ["Kearny Mesa Toyota","AutoNation Toyota","Toyota of El Cajon","Mossy Toyota"],
    "san francisco": ["Stevens Creek Toyota","East Bay Toyota","Marin Toyota","AutoNation Toyota"],
    "seattle": ["Toyota of Seattle","Carter Toyota","Barrier Toyota","Younker Toyota"],
    "portland": ["Ron Tonkin Toyota","Beaverton Toyota","Carr Toyota","AutoNation Toyota"],
    "atlanta": ["AutoNation Toyota","Jim Ellis Toyota","Nalley Toyota","Rick Case Toyota"],
    "new york": ["Paragon Toyota","White Plains Toyota","Smithtown Toyota","Rallye Toyota"],
    "queens": ["Paragon Toyota","White Plains Toyota","Bay Ridge Toyota","Atlantic Toyota"],
    "miami": ["AutoNation Toyota","Braman Toyota","Maroone Toyota","Headquarter Toyota"],
    "orlando": ["AutoNation Toyota","Holler Toyota","Greenway Toyota","Toyota of Orlando"],
    "tampa": ["AutoNation Toyota","Reeves Toyota","Brandon Toyota","Stadium Toyota"],
    "jacksonville": ["AutoNation Toyota","Nimnicht Toyota","Greenway Toyota","Toyota of Orange Park"],
    "charlotte": ["Hendrick Toyota","AutoNation Toyota","Toyota of Concord","Parks Toyota"],
    "nashville": ["AutoNation Toyota","Crest Toyota","Royal Toyota","Toyota of Cool Springs"],
    "boston": ["Herb Chambers Toyota","Prime Toyota","Ira Toyota","Bernardi Toyota"],
    "detroit": ["LaFontaine Toyota","Suburban Toyota","AutoNation Toyota","Sellers Toyota"],
    "cleveland": ["Montrose Toyota","AutoNation Toyota","Ganley Toyota","Spitzer Toyota"],
    "columbus": ["Germain Toyota","Byers Toyota","Jeff Wyler Toyota","Toyota of Marysville"],
    "pittsburgh": ["Cochran Toyota","AutoNation Toyota","Baierl Toyota","Bowser Toyota"],
    "philadelphia": ["Toyota of Cherry Hill","Fred Beans Toyota","AutoNation Toyota","Sloane Toyota"],
    "baltimore": ["Len Stoler Toyota","Brown's Toyota","AutoNation Toyota","Koons Toyota"],
    "washington": ["Koons Toyota","AutoNation Toyota","Pohanka Toyota","Ourisman Toyota"],
    "dc": ["Koons Toyota","AutoNation Toyota","Pohanka Toyota","Ourisman Toyota"],
    "minneapolis": ["Luther Toyota","Morrie's Toyota","Walser Toyota","Inver Grove Toyota"],
    "st. louis": ["Bommarito Toyota","Lou Fusz Toyota","AutoNation Toyota","Frank Leta Toyota"],
    "kansas city": ["Toyota of Kansas City","Summit Toyota","Cable Dahmer Toyota","AutoNation Toyota"],
    "milwaukee": ["Russ Darrow Toyota","Wilde Toyota","Bergstrom Toyota","AutoNation Toyota"],
    "omaha": ["Baxter Toyota","Woodhouse Toyota","AutoNation Toyota","Toyota of Omaha"],
    "las vegas": ["Findlay Toyota","AutoNation Toyota","Chapman Toyota","Henderson Toyota"],
    "salt lake city": ["Larry H. Miller Toyota","Mark Miller Toyota","AutoNation Toyota","Nate Wade Toyota"],
    "albuquerque": ["Fiesta Toyota","Quality Toyota","Stewart Toyota","Melloy Toyota"],
    "austin": ["Nyle Maxwell Toyota","Capital Toyota","Round Rock Toyota","Covert Toyota"],
    "san antonio": ["Ancira Toyota","Cavender Toyota","Gunn Toyota","AutoNation Toyota"],
    "oklahoma city": ["Bob Moore Toyota","David Stanley Toyota","AutoNation Toyota","Fowler Toyota"],
    "memphis": ["AutoNation Toyota","Wolfchase Toyota","Covington Pike Toyota","Serra Toyota"],
    "louisville": ["Oxmoor Toyota","Jeff Wyler Toyota","AutoNation Toyota","Toyota of Clarksville"],
    "birmingham": ["AutoNation Toyota","Tameron Toyota","Serra Toyota","Gary Smith Toyota"],
    "honolulu": ["Cutter Toyota","Servco Toyota","Island Toyota","AutoNation Toyota"],
  },
  "nissan": {
    "indianapolis": ["Andy Mohr Nissan","Tom Wood Nissan","Dreyer & Reinbold Nissan","Ray Skillman Nissan"],
    "chicago": ["McGrath Nissan","Elgin Nissan","Naperville Nissan","AutoNation Nissan"],
    "dallas": ["AutoNation Nissan","Classic Nissan","Huffines Nissan","David McDavid Nissan"],
    "houston": ["AutoNation Nissan","Gillman Nissan","Sterling McCall Nissan","Mac Haik Nissan"],
    "denver": ["Emich Nissan","Groove Nissan","Larry H. Miller Nissan","Medved Nissan"],
    "phoenix": ["AutoNation Nissan","Camelback Nissan","Earnhardt Nissan","Chapman Nissan"],
    "los angeles": ["AutoNation Nissan","Keyes Nissan","Puente Hills Nissan","Galpin Nissan"],
    "san diego": ["AutoNation Nissan","El Cajon Nissan","Mossy Nissan","Kearny Mesa Nissan"],
    "seattle": ["AutoNation Nissan","Carter Nissan","Barrier Nissan","Younker Nissan"],
    "atlanta": ["AutoNation Nissan","Jim Ellis Nissan","Nalley Nissan","Rick Case Nissan"],
    "new york": ["Paragon Nissan","White Plains Nissan","Smithtown Nissan","Rallye Nissan"],
    "queens": ["Paragon Nissan","Atlantic Nissan","Bay Ridge Nissan","White Plains Nissan"],
    "miami": ["AutoNation Nissan","Braman Nissan","Maroone Nissan","Headquarter Nissan"],
    "orlando": ["AutoNation Nissan","Holler Nissan","Greenway Nissan","Nissan of Orlando"],
    "tampa": ["AutoNation Nissan","Reeves Nissan","Brandon Nissan","Stadium Nissan"],
    "boston": ["Herb Chambers Nissan","Prime Nissan","Ira Nissan","Quirk Nissan"],
    "charlotte": ["Hendrick Nissan","AutoNation Nissan","Nissan of Concord","Parks Nissan"],
    "nashville": ["AutoNation Nissan","Crest Nissan","Royal Nissan","Nissan of Cool Springs"],
    "minneapolis": ["Luther Nissan","Morrie's Nissan","Walser Nissan","Inver Grove Nissan"],
    "st. louis": ["Bommarito Nissan","Lou Fusz Nissan","AutoNation Nissan","Frank Leta Nissan"],
    "las vegas": ["Findlay Nissan","AutoNation Nissan","Chapman Nissan","Henderson Nissan"],
    "salt lake city": ["Larry H. Miller Nissan","Mark Miller Nissan","AutoNation Nissan","Nate Wade Nissan"],
    "austin": ["Nyle Maxwell Nissan","Capital Nissan","Round Rock Nissan","Covert Nissan"],
    "san antonio": ["Ancira Nissan","Cavender Nissan","Gunn Nissan","AutoNation Nissan"],
  },
  "hyundai": {
    "indianapolis": ["Andy Mohr Hyundai","Tom Wood Hyundai","Dreyer & Reinbold Hyundai","Ray Skillman Hyundai"],
    "chicago": ["McGrath Hyundai","Elgin Hyundai","Naperville Hyundai","AutoNation Hyundai"],
    "dallas": ["AutoNation Hyundai","Classic Hyundai","Huffines Hyundai","David McDavid Hyundai"],
    "houston": ["AutoNation Hyundai","Gillman Hyundai","Sterling McCall Hyundai","Mac Haik Hyundai"],
    "denver": ["Emich Hyundai","Groove Hyundai","Larry H. Miller Hyundai","Medved Hyundai"],
    "phoenix": ["AutoNation Hyundai","Camelback Hyundai","Earnhardt Hyundai","Chapman Hyundai"],
    "los angeles": ["AutoNation Hyundai","Keyes Hyundai","Puente Hills Hyundai","Galpin Hyundai"],
    "seattle": ["AutoNation Hyundai","Carter Hyundai","Barrier Hyundai","Younker Hyundai"],
    "atlanta": ["AutoNation Hyundai","Jim Ellis Hyundai","Nalley Hyundai","Rick Case Hyundai"],
    "new york": ["Paragon Hyundai","White Plains Hyundai","Smithtown Hyundai","Rallye Hyundai"],
    "miami": ["AutoNation Hyundai","Braman Hyundai","Maroone Hyundai","Headquarter Hyundai"],
    "boston": ["Herb Chambers Hyundai","Prime Hyundai","Ira Hyundai","Quirk Hyundai"],
    "nashville": ["AutoNation Hyundai","Crest Hyundai","Royal Hyundai","Hyundai of Cool Springs"],
    "charlotte": ["Hendrick Hyundai","AutoNation Hyundai","Hyundai of Concord","Parks Hyundai"],
    "minneapolis": ["Luther Hyundai","Morrie's Hyundai","Walser Hyundai","Inver Grove Hyundai"],
    "las vegas": ["Findlay Hyundai","AutoNation Hyundai","Chapman Hyundai","Henderson Hyundai"],
    "salt lake city": ["Larry H. Miller Hyundai","Mark Miller Hyundai","AutoNation Hyundai","Nate Wade Hyundai"],
    "austin": ["Nyle Maxwell Hyundai","Capital Hyundai","Round Rock Hyundai","Covert Hyundai"],
    "san antonio": ["Ancira Hyundai","Cavender Hyundai","Gunn Hyundai","AutoNation Hyundai"],
  },
  "kia": {
    "indianapolis": ["Andy Mohr Kia","Tom Wood Kia","Dreyer & Reinbold Kia","Ray Skillman Kia"],
    "chicago": ["McGrath Kia","Elgin Kia","Naperville Kia","AutoNation Kia"],
    "dallas": ["AutoNation Kia","Classic Kia","Huffines Kia","David McDavid Kia"],
    "houston": ["AutoNation Kia","Gillman Kia","Sterling McCall Kia","Mac Haik Kia"],
    "denver": ["Emich Kia","Groove Kia","Larry H. Miller Kia","Medved Kia"],
    "phoenix": ["AutoNation Kia","Camelback Kia","Earnhardt Kia","Chapman Kia"],
    "los angeles": ["AutoNation Kia","Keyes Kia","Puente Hills Kia","Galpin Kia"],
    "seattle": ["AutoNation Kia","Carter Kia","Barrier Kia","Younker Kia"],
    "atlanta": ["AutoNation Kia","Jim Ellis Kia","Nalley Kia","Rick Case Kia"],
    "new york": ["Paragon Kia","White Plains Kia","Smithtown Kia","Rallye Kia"],
    "miami": ["AutoNation Kia","Braman Kia","Maroone Kia","Headquarter Kia"],
    "boston": ["Herb Chambers Kia","Prime Kia","Ira Kia","Quirk Kia"],
    "nashville": ["AutoNation Kia","Crest Kia","Royal Kia","Kia of Cool Springs"],
    "minneapolis": ["Luther Kia","Morrie's Kia","Walser Kia","Inver Grove Kia"],
    "las vegas": ["Findlay Kia","AutoNation Kia","Chapman Kia","Henderson Kia"],
    "austin": ["Nyle Maxwell Kia","Capital Kia","Round Rock Kia","Covert Kia"],
    "san antonio": ["Ancira Kia","Cavender Kia","Gunn Kia","AutoNation Kia"],
  },
  "jeep": {
    "indianapolis": ["Andy Mohr CDJR","Tom Wood CDJR","Ray Skillman CDJR","Mike Anderson CDJR"],
    "chicago": ["McGrath Jeep","Elgin Jeep","Naperville Jeep","AutoNation Chrysler Jeep"],
    "dallas": ["AutoNation Chrysler Jeep","Classic Jeep","Huffines Jeep","David McDavid Jeep"],
    "houston": ["AutoNation Chrysler Jeep","Gillman Jeep","Sterling McCall Jeep","Mac Haik Jeep"],
    "denver": ["Emich Chrysler Jeep","Groove Jeep","Larry H. Miller Jeep","Medved Jeep"],
    "phoenix": ["AutoNation Chrysler Jeep","Camelback Jeep","Earnhardt Jeep","Chapman Jeep"],
    "los angeles": ["AutoNation Chrysler Jeep","Keyes Jeep","Puente Hills Jeep","Galpin Jeep"],
    "new york": ["Paragon Jeep","White Plains Jeep","Smithtown Jeep","Rallye Jeep"],
    "miami": ["AutoNation Chrysler Jeep","Braman Jeep","Maroone Jeep","Headquarter Jeep"],
    "atlanta": ["AutoNation Chrysler Jeep","Jim Ellis Jeep","Nalley Jeep","Rick Case Jeep"],
    "nashville": ["AutoNation Chrysler Jeep","Crest Jeep","Royal Jeep","Jeep of Cool Springs"],
    "las vegas": ["Findlay Chrysler Jeep","AutoNation Chrysler Jeep","Chapman Jeep","Henderson Chrysler Jeep"],
    "austin": ["Nyle Maxwell CDJR","Capital Chrysler Jeep","Round Rock Chrysler Jeep","Covert Chrysler Jeep"],
    "appleton city": ["Osage CDJR","Harrisonville CDJR","Nevada CDJR","Butler County CDJR"],
  },
  "ram": {
    "indianapolis": ["Andy Mohr RAM","Tom Wood RAM","Ray Skillman RAM","Mike Anderson RAM"],
    "chicago": ["McGrath RAM","Elgin RAM","Naperville RAM","AutoNation RAM"],
    "dallas": ["AutoNation RAM","Classic RAM","Huffines RAM","David McDavid RAM"],
    "houston": ["AutoNation RAM","Gillman RAM","Sterling McCall RAM","Mac Haik RAM"],
    "denver": ["Emich RAM","Groove RAM","Larry H. Miller RAM","Medved RAM"],
    "phoenix": ["AutoNation RAM","Camelback RAM","Earnhardt RAM","Chapman RAM"],
    "los angeles": ["AutoNation RAM","Keyes RAM","Puente Hills RAM","Galpin RAM"],
    "appleton city": ["Osage CDJR","Harrisonville CDJR","Nevada CDJR","Butler County CDJR"],
    "nashville": ["AutoNation RAM","Crest RAM","Royal RAM","RAM of Cool Springs"],
    "las vegas": ["Findlay RAM","AutoNation RAM","Chapman RAM","Henderson RAM"],
    "austin": ["Nyle Maxwell RAM","Capital RAM","Round Rock RAM","Covert RAM"],
    "san antonio": ["Ancira RAM","Cavender RAM","Gunn RAM","AutoNation RAM"],
  },
  "bmw": {
    "indianapolis": ["BMW of Indianapolis","Tom Wood BMW","Dreyer & Reinbold BMW","AutoNation BMW"],
    "chicago": ["BMW of Orland Park","Elmhurst BMW","AutoNation BMW","McGrath BMW"],
    "dallas": ["Park Place BMW","AutoNation BMW","Classic BMW","BMW of Dallas"],
    "houston": ["BMW of Houston North","Sterling McCall BMW","AutoNation BMW","Momentum BMW"],
    "denver": ["BMW of Denver","Schomp BMW","AutoNation BMW","Phil Long BMW"],
    "phoenix": ["AutoNation BMW","Camelback BMW","BMW of Scottsdale","Chapman BMW"],
    "los angeles": ["BMW of Beverly Hills","AutoNation BMW","Rusnak BMW","South Bay BMW"],
    "san diego": ["AutoNation BMW","BMW of El Cajon","Kearny Mesa BMW","Pacific BMW"],
    "san francisco": ["BMW of San Francisco","East Bay BMW","Marin BMW","AutoNation BMW"],
    "seattle": ["BMW of Seattle","AutoNation BMW","BMW of Bellevue","Carter BMW"],
    "new york": ["BMW of Manhattan","Rallye BMW","White Plains BMW","Smithtown BMW"],
    "miami": ["AutoNation BMW","Braman BMW","Fields BMW","BMW of Coral Gables"],
    "atlanta": ["AutoNation BMW","Jim Ellis BMW","Fields BMW","BMW of Atlanta"],
    "boston": ["Herb Chambers BMW","Prime BMW","Ira BMW","Bernardi BMW"],
    "nashville": ["AutoNation BMW","Crest BMW","Royal BMW","BMW of Nashville"],
    "las vegas": ["Findlay BMW","AutoNation BMW","Chapman BMW","Henderson BMW"],
  },
  "mercedes": {
    "indianapolis": ["Mercedes-Benz of Indianapolis","Tom Wood Mercedes-Benz","AutoNation Mercedes-Benz","Dreyer & Reinbold Mercedes-Benz"],
    "chicago": ["Mercedes-Benz of Chicago","Loeber Motors","AutoNation Mercedes-Benz","McGrath Mercedes-Benz"],
    "dallas": ["Park Place Mercedes-Benz","AutoNation Mercedes-Benz","Mercedes-Benz of Dallas","Classic Mercedes-Benz"],
    "houston": ["Mercedes-Benz of Houston","Sterling McCall Mercedes-Benz","AutoNation Mercedes-Benz","Momentum Mercedes-Benz"],
    "denver": ["Mercedes-Benz of Denver","AutoNation Mercedes-Benz","Phil Long Mercedes-Benz","Schomp Mercedes-Benz"],
    "phoenix": ["AutoNation Mercedes-Benz","Camelback Mercedes-Benz","Mercedes-Benz of Scottsdale","Chapman Mercedes-Benz"],
    "los angeles": ["Mercedes-Benz of Beverly Hills","AutoNation Mercedes-Benz","Rusnak Mercedes-Benz","South Bay Mercedes-Benz"],
    "new york": ["Mercedes-Benz of Manhattan","Rallye Mercedes-Benz","White Plains Mercedes-Benz","Mercedes-Benz of Smithtown"],
    "miami": ["AutoNation Mercedes-Benz","Braman Mercedes-Benz","Fields Mercedes-Benz","Mercedes-Benz of Coral Gables"],
    "atlanta": ["AutoNation Mercedes-Benz","Jim Ellis Mercedes-Benz","Fields Mercedes-Benz","Mercedes-Benz of Atlanta"],
    "seattle": ["Mercedes-Benz of Seattle","AutoNation Mercedes-Benz","Mercedes-Benz of Bellevue","Carter Mercedes-Benz"],
    "boston": ["Herb Chambers Mercedes-Benz","Prime Mercedes-Benz","Ira Mercedes-Benz","Bernardi Mercedes-Benz"],
    "nashville": ["AutoNation Mercedes-Benz","Crest Mercedes-Benz","Mercedes-Benz of Nashville","Royal Mercedes-Benz"],
    "las vegas": ["Findlay Mercedes-Benz","AutoNation Mercedes-Benz","Chapman Mercedes-Benz","Henderson Mercedes-Benz"],
  }
};

function getDealers(city, brand) {
  const brandKey = brand.toLowerCase().trim().replace(/-benz$/, '').replace(/\s+/g, ' ');
  const cityKey = city.toLowerCase().replace(/,.*$/, '').trim();

  // Find brand data — exact then partial
  let brandData = DEALER_DB[brandKey];
  if (!brandData) {
    for (const key of Object.keys(DEALER_DB)) {
      if (brandKey.includes(key) || key.includes(brandKey)) {
        brandData = DEALER_DB[key];
        break;
      }
    }
  }
  // Multi-brand or unknown brand — use Toyota as proxy (most universal)
  if (!brandData) {
    const fallbackBrands = ['toyota','honda','ford','chevrolet'];
    for (const fb of fallbackBrands) {
      if (DEALER_DB[fb] && DEALER_DB[fb][cityKey]) {
        return DEALER_DB[fb][cityKey].map(n => n.replace(fb.charAt(0).toUpperCase()+fb.slice(1), brand === 'Multi-brand' ? '' : brand).replace(/\s+/g,' ').trim());
      }
    }
    // Last resort — generic names
    const cityName = cityKey.charAt(0).toUpperCase() + cityKey.slice(1);
    return [cityName+' Auto Group', cityName+' Motors', 'AutoNation '+cityName, 'Hendrick Automotive'];
  }

  // Exact city match
  if (brandData[cityKey]) return brandData[cityKey];

  // Partial city match
  for (const key of Object.keys(brandData)) {
    if (cityKey.includes(key) || key.includes(cityKey)) return brandData[key];
  }

  // State match — find nearest city in same state
  const stateAbbr = city.toLowerCase().match(/,\s*([a-z]{2})\s*$/);
  if (stateAbbr) {
    const stateMap = {
      'in': 'indianapolis', 'il': 'chicago', 'tx': 'dallas', 'ca': 'los angeles',
      'fl': 'miami', 'ga': 'atlanta', 'wa': 'seattle', 'or': 'portland',
      'ny': 'new york', 'ma': 'boston', 'mi': 'detroit', 'oh': 'columbus',
      'pa': 'philadelphia', 'md': 'baltimore', 'va': 'richmond', 'tn': 'nashville',
      'nc': 'charlotte', 'az': 'phoenix', 'co': 'denver', 'nv': 'las vegas',
      'ut': 'salt lake city', 'mn': 'minneapolis', 'mo': 'st. louis', 'wi': 'milwaukee',
      'ne': 'omaha', 'ia': 'des moines', 'ok': 'oklahoma city', 'la': 'new orleans',
      'al': 'birmingham', 'sc': 'columbia', 'ky': 'louisville', 'nj': 'philadelphia',
      'ct': 'boston', 'nh': 'boston', 'nm': 'albuquerque', 'id': 'boise',
      'ks': 'kansas city', 'ar': 'little rock', 'ms': 'memphis', 'hi': 'honolulu',
      'ak': 'anchorage', 'sd': 'minneapolis', 'nd': 'minneapolis', 'mt': 'denver',
      'wy': 'denver', 'wv': 'richmond', 'me': 'boston', 'vt': 'boston',
      'ri': 'boston', 'de': 'philadelphia', 'dc': 'washington',
    };
    const fallbackCity = stateMap[stateAbbr[1]];
    if (fallbackCity && brandData[fallbackCity]) return brandData[fallbackCity];
  }

  // Generic fallback — brand exists but city not in database
  const cityName = cityKey.charAt(0).toUpperCase() + cityKey.slice(1);
  const brandName = brand.charAt(0).toUpperCase() + brand.slice(1).toLowerCase();
  return [
    'AutoNation '+brandName,
    cityName+' '+brandName,
    brandName+' of '+cityName,
    'Hendrick '+brandName
  ];
}

app.get('/api/competitors', (req, res) => {
  const { city, brand } = req.query;
  if (!city || !brand) return res.json({ competitors: [] });

  const dealers = getDealers(city, brand);
  const competitors = dealers.slice(0, 4).map((name, i) => ({
    name,
    address: city.split(',')[0].trim() + ' area',
    distance: (i + 1) * 6 + Math.round(Math.random() * 4)
  }));

  console.log(`${brand} near ${city}:`, competitors.map(c => c.name).join(', '));
  res.json({ competitors });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log('VINI Tool running on port ' + PORT));
